import { images } from '@/exports/images';
import {
  AccManage,
  Bills,
  Deposit,
  ExchangeRate,
  GlobalPay,
  LegalIcon,
  MXECard,
  OnboardIcon,
  SavingIcon,
  Withdrawal,
} from '../SVGs/Icons';

export const faqData = [
  {
    id: 1,
    title: 'Onboarding',
    icon: <OnboardIcon />,
    articles: 3,
    authorImages: [images.avatar, images.avatar1, images.avatar2],
    url: 'onboarding',
    questions: [
      { qid: 'question1', qtitle: 'How do I onboard on MXE?' },
      { qid: 'question2', qtitle: 'How do I change my phone number on MXE?' },
      {
        qid: 'question3',
        qtitle: 'How do I change my transaction PIN on MXE?',
      },
      { qid: 'question4', qtitle: 'Why should I verify my account?' },
      { qid: 'question5', qtitle: 'How do I verify my account?' },
    ],
  },
  {
    id: 2,
    title: 'Account Management',
    icon: <AccManage />,
    articles: 5,
    authorImages: [images.avatar, images.avatar1, images.avatar2],
    url: 'account-management',
    questions: [
      { qid: 'question1', qtitle: 'How do I change my password on MXE?' },
      { qid: 'question2', qtitle: 'How do I change my phone number on MXE?' },
      {
        qid: 'question3',
        qtitle: 'How do I change my transaction PIN on MXE?',
      },
      { qid: 'question4', qtitle: 'Why should I verify my account?' },
      { qid: 'question5', qtitle: 'How do I verify my account?' },
    ],
  },
  {
    id: 3,
    title: 'Global Payments',
    icon: <GlobalPay />,
    articles: 5,
    authorImages: [
      images.avatar,
      images.avatar1,
      images.avatar2,
      images.avatar4,
    ],
    url: 'global-payments',
    questions: [
      { qid: 'question1', qtitle: 'What is global payments on MXE?' },
      {
        qid: 'question2',
        qtitle: 'How do I change my phone number on MXE?',
      },
      {
        qid: 'question3',
        qtitle: 'How do I change my transaction PIN on MXE?',
      },
      { qid: 'question4', qtitle: 'Why should I verify my account?' },
      { qid: 'question5', qtitle: 'How do I verify my account?' },
    ],
  },
  {
    id: 4,
    title: 'Deposit/Fund Account',
    icon: <Deposit />,
    articles: 6,
    authorImages: [images.avatar, images.avatar1],
    url: 'fund-account',
    questions: [
      { qid: 'question1', qtitle: 'How do I deposite  on MXE?' },
      { qid: 'question2', qtitle: 'How do I fund my account on MXE?' },
      {
        qid: 'question3',
        qtitle: 'How do I change my transaction PIN on MXE?',
      },
      { qid: 'question4', qtitle: 'Why should I verify my account?' },
      { qid: 'question5', qtitle: 'How do I verify my account?' },
    ],
  },
  {
    id: 5,
    title: 'Bill Payment',
    icon: <Bills />,
    articles: 8,
    authorImages: [images.avatar, images.avatar1, images.avatar2],
    url: 'bill-payment',
    questions: [
      { qid: 'question1', qtitle: 'How do I change my password on MXE?' },
      { qid: 'question2', qtitle: 'How do I change my phone number on MXE?' },
      {
        qid: 'question3',
        qtitle: 'How do I change my transaction PIN on MXE?',
      },
      { qid: 'question4', qtitle: 'Why should I verify my account?' },
      { qid: 'question5', qtitle: 'How do I verify my account?' },
    ],
  },
  {
    id: 6,
    title: 'MXE Card',
    icon: <MXECard />,
    articles: 12,
    authorImages: [
      images.avatar,
      images.avatar1,
      images.avatar2,
      images.avatar4,
    ],
    url: 'mxe-card',
    questions: [
      { qid: 'question1', qtitle: 'How do I change my password on MXE?' },
      { qid: 'question2', qtitle: 'How do I change my phone number on MXE?' },
      {
        qid: 'question3',
        qtitle: 'How do I change my transaction PIN on MXE?',
      },
      { qid: 'question4', qtitle: 'Why should I verify my account?' },
      { qid: 'question5', qtitle: 'How do I verify my account?' },
    ],
  },
  {
    id: 7,
    title: 'Exchange Rate',
    icon: <ExchangeRate />,
    articles: 3,
    authorImages: [images.avatar, images.avatar1, images.avatar2],
    url: 'exchange-rate',
    questions: [
      { qid: 'question1', qtitle: 'How do I change my password on MXE?' },
      { qid: 'question2', qtitle: 'How do I change my phone number on MXE?' },
      {
        qid: 'question3',
        qtitle: 'How do I change my transaction PIN on MXE?',
      },
      { qid: 'question4', qtitle: 'Why should I verify my account?' },
      { qid: 'question5', qtitle: 'How do I verify my account?' },
    ],
  },
  {
    id: 8,
    title: 'USD Saving',
    icon: <SavingIcon />,
    articles: 8,
    authorImages: [images.avatar3, images.avatar1],
    url: 'usd-saving',
    questions: [
      { qid: 'question1', qtitle: 'How do I change my password on MXE?' },
      { qid: 'question2', qtitle: 'How do I change my phone number on MXE?' },
      {
        qid: 'question3',
        qtitle: 'How do I change my transaction PIN on MXE?',
      },
      { qid: 'question4', qtitle: 'Why should I verify my account?' },
      { qid: 'question5', qtitle: 'How do I verify my account?' },
    ],
  },
  {
    id: 9,
    title: 'Withdrawals',
    icon: <Withdrawal />,
    articles: 8,
    authorImages: [images.avatar3, images.avatar1],
    url: 'withdrawals',
    questions: [
      { qid: 'question1', qtitle: 'How do I change my password on MXE?' },
      { qid: 'question2', qtitle: 'How do I change my phone number on MXE?' },
      {
        qid: 'question3',
        qtitle: 'How do I change my transaction PIN on MXE?',
      },
      { qid: 'question4', qtitle: 'Why should I verify my account?' },
      { qid: 'question5', qtitle: 'How do I verify my account?' },
    ],
  },
  {
    id: 10,
    title: 'Legal',
    icon: <LegalIcon />,
    articles: 8,
    authorImages: [images.avatar3, images.avatar1],
    url: 'legal',
    questions: [
      { qid: 'question1', qtitle: 'How do I change my password on MXE?' },
      { qid: 'question2', qtitle: 'How do I change my phone number on MXE?' },
      {
        qid: 'question3',
        qtitle: 'How do I change my transaction PIN on MXE?',
      },
      { qid: 'question4', qtitle: 'Why should I verify my account?' },
      { qid: 'question5', qtitle: 'How do I verify my account?' },
    ],
  },
  {
    id: 11,
    title: 'Safety and Security',
    icon: <LegalIcon />,
    articles: 8,
    authorImages: [images.avatar3, images.avatar1],
    url: 'saving-security',
    questions: [
      { qid: 'question1', qtitle: 'How do I change my password on MXE?' },
      { qid: 'question2', qtitle: 'How do I change my phone number on MXE?' },
      {
        qid: 'question3',
        qtitle: 'How do I change my transaction PIN on MXE?',
      },
      { qid: 'question4', qtitle: 'Why should I verify my account?' },
      { qid: 'question5', qtitle: 'How do I verify my account?' },
    ],
  },
];
